version: "3"  
services:  
  cassandra:
    restart: always
    image: cassandra:3.11.5
    container_name: cassandra-db
    volumes: 
      - /opt/data-cassandra-db:/var/lib/cassandra
    ports: 
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
    